services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false


  lindesbs\pageyaml\Controller\:
    resource: '../../Controller'
    tags: ['controller.service_arguments']



  lindesbs\pageyaml\Classes\DCAManage:
    arguments: []